# =========================================
# Homelab SSH Config
# =========================================

# -------------------------
# Potent Pi Zero
# -------------------------

Host pp0
    HostName 10.100.0.10
    User potentpi0
    password uranium32

# -------------------------
# Potent Pi 1
# -------------------------

Host pp1
    HostName 10.100.0.11
    User potentpi1
    password uranium32

# -------------------------
# Potent Pi 2
# -------------------------

Host pp2
    HostName 10.100.0.12
    User potentpi2
    password uranium32

# -------------------------
# Potent Pi 3
# -------------------------

Host pp3
    HostName 10.100.0.13
    User potentpi3
    password uranium32

# -------------------------
# Potent Pi 4
# -------------------------

Host pp4
    HostName 10.100.0.14
    User potentpi4
    password uranium32

# -------------------------
# Potent Pi 5
# -------------------------

Host pp5
    HostName 10.10.25.21
    User root
    password uranium32

# -------------------------
# Potent Pi 6
# -------------------------

Host pp6
    HostName 10.10.25.20
    User potentpi6
    password uranium32

# -------------------------
# TrueNAS
# -------------------------

Host truenas
    HostName 10.100.0.15
    User truenas_admin
    password uranium32

# -------------------------
# Aesir Cluster
# -------------------------

Host aesir
    HostName 10.100.0.30
    User root
    password uranium32

# -------------------------
# Vanir Cluster
# -------------------------

Host vanir
    HostName 10.100.0.61
    User root
    password uranium32

# -------------------------
# SimulationCraft VM
# -------------------------

Host workstation
    HostName 10.100.0.71
    User jmay
    Password welcome123

# -------------------------
# Generic Defaults
# -------------------------

Host *
    ServerAliveInterval 30
    ServerAliveCountMax 3
    Compression yes